### ISSUE TITLE
Shoud we update current repository ?

### ISSUE THREAD

**Issue by CrazyBBer** [micro/cli#2]
This branch is 4 commits ahead, 442 commits behind urfave:master.
Should we update this reposotory from the upstream  ?
 Is it nesessary ?

**Comment by asim** [comment]
Unrelated. Can I ask what the status of Honeywell's usage of micro is? Is it in production?

**Comment by CrazyBBer** [comment]
With a glancing , it looks some changes  from upstream useful ,such as bug fix , ,feature enhancement ,maybe ,it's worth to take a little time to check.

**Comment by asim** [comment]
Do you want to investigate updating with the latest commits? This is not something that's adversely effecting the other users of micro. If there's something in there you feel you need or a critical bug fix then please mention it but otherwise considering flag parsing is a very minimal part I'm not sure its needed.

**Comment by CrazyBBer** [comment]
I'm one coder from some team you can touch with ,it looks other buddies using github only a little ,i will get to know it.
